export const DECISION_INBOX_CSS = String.raw`
.dsh-di-dock{display:flex;justify-content:center;width:100%;padding:0 calc(var(--dsh-composer-side-clearance,0px) + 16px) 8px;box-sizing:border-box;color:var(--dsw-alias-label-primary)}
.dsh-di-card{width:100%;max-width:var(--dsh-chat-content-width);overflow:hidden;border:1px solid var(--dsw-alias-border-l2-darkmode-thin);border-radius:16px;background:var(--dsw-specific-input-major);box-shadow:var(--dsw-shadow-lv2);box-sizing:border-box;animation:dsh-di-in 160ms ease-out}
.dsh-di-toggle{display:flex;align-items:center;gap:9px;width:100%;min-height:42px;padding:9px 14px;border:0;background:transparent;color:inherit;text-align:left;cursor:pointer}
.dsh-di-toggle:hover{background:var(--dsw-alias-interactive-bg-hover)}
.dsh-di-dot{width:8px;height:8px;flex:0 0 8px;border-radius:50%;background:var(--dsw-alias-state-warn-primary);box-shadow:0 0 0 3px var(--dsw-alias-state-warn-tertiary)}
.dsh-di-label{font-size:14px;font-weight:500;line-height:22px}.dsh-di-count{display:grid;place-items:center;min-width:20px;height:20px;padding:0 6px;border-radius:999px;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-label-secondary);font-size:12px;box-sizing:border-box}
.dsh-di-spacer{flex:1}.dsh-di-chevron{display:inline-flex;color:var(--dsw-alias-label-tertiary);transition:transform 120ms ease}.dsh-di-chevron[data-open=true]{transform:rotate(180deg)}
.dsh-di-body{padding:4px 14px 14px;border-top:1px solid var(--dsw-alias-border-l2-darkmode-thin)}
.dsh-di-meta{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:10px 2px 7px;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:16px}
.dsh-di-question{margin:0 2px 8px;font-size:15px;font-weight:500;line-height:22px;overflow-wrap:anywhere}
.dsh-di-options{display:flex;flex-direction:column;gap:2px}
.dsh-di-option{display:flex;align-items:flex-start;gap:9px;width:100%;min-height:40px;padding:8px;border:1px solid transparent;border-radius:11px;background:transparent;color:inherit;text-align:left;cursor:pointer;box-sizing:border-box}
.dsh-di-option:hover:not(:disabled),.dsh-di-option:focus-visible{border-color:var(--dsw-alias-border-l2);background:var(--dsw-alias-interactive-bg-hover);outline:none}.dsh-di-option:disabled{opacity:.55;cursor:default}
.dsh-di-number{display:grid;place-items:center;flex:0 0 20px;width:20px;height:20px;margin-top:1px;border-radius:6px;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:500}
.dsh-di-option-copy{display:flex;align-items:baseline;flex-wrap:wrap;gap:2px 7px;min-width:0;line-height:22px}.dsh-di-option-label{font-size:14px;font-weight:500}.dsh-di-description{color:var(--dsw-alias-label-tertiary);font-size:13px}.dsh-di-recommended{padding:0 5px;border-radius:6px;background:var(--dsw-specific-sidebar-nav-item-active-accent);color:var(--dsw-alias-button-info-fill);font-size:10px;font-weight:600;line-height:17px}
.dsh-di-custom-trigger{margin-top:3px}.dsh-di-custom{display:flex;align-items:center;gap:8px;margin-top:6px;padding:7px 8px;border:1px solid var(--dsw-alias-border-l2);border-radius:11px;background:var(--dsw-alias-bg-module-platform)}
.dsh-di-input{min-width:0;flex:1;padding:0;border:0;outline:0;background:transparent;color:var(--dsw-alias-label-primary);caret-color:var(--dsw-alias-state-business-primary);font:inherit;font-size:14px;line-height:24px}.dsh-di-input::placeholder{color:var(--dsw-alias-label-caption)}
.dsh-di-submit{height:28px;padding:0 11px;border:0;border-radius:8px;background:var(--dsw-alias-label-primary);color:var(--dsw-alias-label-primary-foreground);font-size:12px;font-weight:600;cursor:pointer}.dsh-di-submit:disabled{opacity:.45;cursor:default}
.dsh-di-retry{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 10px;border-radius:10px;background:var(--dsw-alias-state-warn-tertiary);color:var(--dsw-alias-state-warn-label);font-size:13px}.dsh-di-retry button{padding:4px 9px;border:0;border-radius:7px;background:var(--dsw-alias-state-warn-primary);color:var(--dsw-alias-label-primary-foreground);cursor:pointer}
.dsh-di-footer{display:flex;align-items:center;gap:8px;margin-top:10px;min-height:24px}.dsh-di-nav{display:flex;align-items:center;gap:5px}.dsh-di-nav button{display:grid;place-items:center;width:24px;height:24px;padding:0;border:0;border-radius:999px;background:transparent;color:var(--dsw-alias-label-tertiary);cursor:pointer}.dsh-di-nav button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dsh-di-nav button:disabled{opacity:.35;cursor:default}.dsh-di-progress{font-size:12px;color:var(--dsw-alias-label-secondary)}
.dsh-di-export{height:24px;padding:0 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;background:transparent;color:var(--dsw-alias-label-secondary);font-size:11px;cursor:pointer}.dsh-di-export:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dsh-di-export:disabled{opacity:.55;cursor:default}
.dsh-di-feedback{min-width:0;flex:1;color:var(--dsw-alias-state-error-primary);font-size:11px;line-height:16px;text-align:right;overflow-wrap:anywhere}.dsh-di-feedback[data-kind=success]{color:var(--dsw-alias-state-success-primary)}
@keyframes dsh-di-in{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}
@media(max-width:720px){.dsh-di-dock{padding-left:8px;padding-right:8px}.dsh-di-card{border-radius:14px}.dsh-di-body{padding-left:10px;padding-right:10px}}
@media(prefers-reduced-motion:reduce){.dsh-di-card{animation:none}.dsh-di-chevron{transition:none}}
`
